services:
  db:
    image: postgres:16-alpine
    container_name: app_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-app}",
          "-d",
          "${POSTGRES_DB:-appdb}",
        ]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: app_backend
    environment:
      PORT: 8000
      # DATABASE_URL: postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-secret}@db:5432/${POSTGRES_DB:-appdb}
      DATABASE_URL: postgres://app:secret@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: app_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
