import "./styles.css";

import "./components/button.ts";
import "./components/field.ts";
import "./components/create-post.ts";
import "./components/select.ts";

// import "./select.js";
// import "./textarea.js";
// import "./checkbox.js";
// import "./radio.js";
// import "./switch.js";
// import "./field.js";
// import "./form.js";
// import "./alert.js";
// import "./modal.js";
// import "./dropdown.js";
// import "./pagination.js";
// import "./table.js";
// import "./tooltip.js";
// import "./popover.js";
// import "./collapse.js";
// import "./carousel.js";
// import "./accordion.js";
// import "./progress.js";
// import "./spinner.js";
// import "./toast.js";
// import "./badge.js";
// import "./breadcrumb.js";
// import "./card.js";
// import "./list-group.js";
// import "./navbar.js";
